apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadphcn1316-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadphcn1316-tenant-component
    app.kubernetes.io/part-of: loadphcn1316-tenant-app
  name: loadphcn1316-tenant-component
  namespace: loadphcn1316-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadphcn1316-tenant-component
    weight: null
status: {}
